namespace TextAdventure.Sample.Zork;

internal readonly record struct RoomDef(string Id, string Name, string Description, bool Dark);

/// <summary>All 110 Zork I locations with Infocom-style room descriptions.</summary>
internal static class ZorkMapData
{
    internal static RoomDef[] AllRooms =>
    [
        // Surface (16)
        new(ZorkIds.WestOfHouse, "West of House",
            "You are standing in an open field west of a white house, with a boarded front door.", false),
        new(ZorkIds.NorthOfHouse, "North of House",
            "You are facing the north side of a white house. There is no door here, and all the windows are boarded up. To the north a narrow path winds through the trees.", false),
        new(ZorkIds.SouthOfHouse, "South of House",
            "You are facing the south side of a white house. There is no door here, and all the windows are boarded.", false),
        new(ZorkIds.EastOfHouse, "Behind House",
            "You are behind the white house. A path leads into the forest to the east. In one corner of the house there is a small window which is slightly ajar.", false),
        new(ZorkIds.Forest1, "Forest",
            "This is a forest, with trees in all directions. To the east, there appears to be sunlight.", false),
        new(ZorkIds.Forest2, "Forest",
            "This is a dimly lit forest, with large trees all around.", false),
        new(ZorkIds.Forest3, "Forest",
            "The forest thins out, revealing impassable mountains.", false),
        new(ZorkIds.Forest4, "Forest",
            "This is a dimly lit forest, with large trees all around.", false),
        new(ZorkIds.ForestPath, "Forest Path",
            "This is a path winding through a dimly lit forest. The path heads north-south here. One particularly large tree with some low branches stands at the edge of the path.", false),
        new(ZorkIds.Clearing1, "Clearing",
            "You are in a clearing, with a forest surrounding you on all sides. A path leads south.", false),
        new(ZorkIds.Clearing2, "Clearing",
            "You are in a small clearing in a well marked forest path that extends to the east and west.", false),
        new(ZorkIds.UpATree, "Up a Tree",
            "You are about 10 feet above the ground nestled among some large branches. The nearest branch above you is above your reach.", false),
        new(ZorkIds.StoneBarrow, "Stone Barrow",
            "You are standing in front of a massive barrow of stone. In the east face is a huge stone door which is open. You cannot see into the dark of the tomb.", false),
        new(ZorkIds.CanyonView, "Canyon View",
            "You are at the top of the Great Canyon on its west wall. From here there is a marvelous view of the canyon and parts of the Frigid River upstream. Across the canyon, the walls of the White Cliffs join the mighty ramparts of the Flathead Mountains to the east. Following the Canyon upstream to the north, Aragain Falls may be seen, complete with rainbow. The mighty Frigid River flows out from a great dark cavern. To the west and south can be seen an immense forest, stretching for miles around. A path leads northwest. It is possible to climb down into the canyon from here.", false),
        new(ZorkIds.RockyLedge, "Rocky Ledge",
            "You are on a ledge about halfway up the wall of the river canyon. You can see from here that the main flow from Aragain Falls twists along a passage which it is impossible for you to enter. Below you is the canyon bottom. Above you is more cliff, which appears climbable.", false),
        new(ZorkIds.CanyonBottom, "Canyon Bottom",
            "You are beneath the walls of the river canyon which may be climbable here. The lesser part of the runoff of Aragain Falls flows by below. To the north is a narrow path.", false),

        // House (4)
        new(ZorkIds.Kitchen, "Kitchen",
            "You are in the kitchen of the white house. A table seems to have been used recently for the preparation of food. A passage leads to the west and a dark staircase can be seen leading upward. A dark chimney leads down and to the east is a small window which is open.", false),
        new(ZorkIds.LivingRoom, "Living Room",
            "You are in the living room. There is a doorway here, a wooden staircase leading upward, a trophy case, and a large oriental rug which covers the floor.", false),
        new(ZorkIds.Attic, "Attic",
            "This is the attic. The only exit is a stairway leading down. On the east end is a large openable window.", true),
        new(ZorkIds.StrangePassage, "Strange Passage",
            "This is a long passage. To the west is one entrance. On the east there is an old wooden door, with a large opening in it (about cyclops sized).", true),

        // Upper dungeon (12)
        new(ZorkIds.Cellar, "Cellar",
            "You are in a dark and damp cellar with a narrow passageway leading north, and a crawlway to the south. On the west is the bottom of a steep metal ramp which is unclimbable.", true),
        new(ZorkIds.EastOfChasm, "East of Chasm",
            "You are on the east edge of a chasm, the bottom of which cannot be seen. A narrow passage goes north, and the path you are on continues to the east.", true),
        new(ZorkIds.Gallery, "Gallery",
            "This is an art gallery. Most of the paintings have been stolen by vandals with exceptional taste. The vandals left through either the north or west exits.", false),
        new(ZorkIds.Studio, "Studio",
            "This appears to have been an artist's studio. The walls and floors are splattered with paints of 69 different colors. Strangely enough, nothing of value is hanging here. At the south end of the room is an open door (also covered with paint). A dark and narrow chimney leads up from a fireplace; although you might be able to get up it, it seems unlikely you could get back down.", true),
        new(ZorkIds.TrollRoom, "The Troll Room",
            "This is a small room with passages to the east and south and a forbidding hole leading west. Bloodstains and deep scratches (perhaps made by an axe) mar the walls.", true),
        new(ZorkIds.EwPassage, "East-West Passage",
            "This is a narrow east-west passageway. There is a narrow stairway leading down at the north end of the room.", true),
        new(ZorkIds.RoundRoom, "Round Room",
            "This is a circular stone room with passages in all directions. Several of them have unfortunately been blocked by cave-ins.", true),
        new(ZorkIds.EngravingsCave, "Engravings Cave",
            "You have entered a low cave with passages leading northwest and east.", true),
        new(ZorkIds.DomeRoom, "Dome Room",
            "You are at the periphery of a large dome, which has been partially blocked by a cave-in.", true),
        new(ZorkIds.LoudRoom, "Loud Room",
            "This is a large room, whose east wall is solid rock. A number of errors north and other messages south, west, and up.", true),
        new(ZorkIds.DeepCanyon, "Deep Canyon",
            "You are on the south edge of a deep canyon. Passages lead to the east, northwest and southwest. A stairway leads down.", true),
        new(ZorkIds.GratingRoom, "Grating Room",
            "You are in a small room near the maze. There are twisty passages in the immediate vicinity.", true),

        // Maze (19 + 3 dead ends)
        new(ZorkIds.Maze1, "Maze", "This is part of a maze of twisty little passages, all alike.", true),
        new(ZorkIds.Maze2, "Maze", "This is part of a maze of twisty little passages, all alike.", true),
        new(ZorkIds.Maze3, "Maze", "This is part of a maze of twisty little passages, all alike.", true),
        new(ZorkIds.Maze4, "Maze", "This is part of a maze of twisty little passages, all alike.", true),
        new(ZorkIds.Maze5, "Maze",
            "This is part of a maze of twisty little passages, all alike. A skeleton, probably the remains of a luckless adventurer, lies here.", true),
        new(ZorkIds.Maze6, "Maze", "This is part of a maze of twisty little passages, all alike.", true),
        new(ZorkIds.Maze7, "Maze", "This is part of a maze of twisty little passages, all alike.", true),
        new(ZorkIds.Maze8, "Maze", "This is part of a maze of twisty little passages, all alike.", true),
        new(ZorkIds.Maze9, "Maze", "This is part of a maze of twisty little passages, all alike.", true),
        new(ZorkIds.Maze10, "Maze", "This is part of a maze of twisty little passages, all alike.", true),
        new(ZorkIds.Maze11, "Dead End", "You have come to a dead end in the maze.", true),
        new(ZorkIds.Maze12, "Maze", "This is part of a maze of twisty little passages, all alike.", true),
        new(ZorkIds.Maze13, "Maze", "This is part of a maze of twisty little passages, all alike.", true),
        new(ZorkIds.Maze14, "Maze", "This is part of a maze of twisty little passages, all alike.", true),
        new(ZorkIds.Maze15, "Maze", "This is part of a maze of twisty little passages, all alike.", true),
        new(ZorkIds.Maze16, "Dead End", "You have come to a dead end in the maze.", true),
        new(ZorkIds.Maze17, "Maze", "This is part of a maze of twisty little passages, all alike.", true),
        new(ZorkIds.Maze18, "Dead End", "You have come to a dead end in the maze.", true),
        new(ZorkIds.Maze19, "Dead End", "You have come to a dead end in the maze.", true),

        // Lower dungeon / temple (18)
        new(ZorkIds.CyclopsRoom, "Cyclops Room",
            "This room has an exit on the northwest, and a staircase leading up. A cyclops, who looks prepared to eat horses, blocks the staircase.", true),
        new(ZorkIds.TreasureRoom, "Treasure Room",
            "This is a large room, whose east wall is solid granite. A number of discarded bags, which crumble at your touch, are scattered about on the floor. There is an exit down a staircase.", true),
        new(ZorkIds.NsPassage, "North-South Passage",
            "This is a high north-south passage, which forks to the northeast.", true),
        new(ZorkIds.Chasm, "Chasm",
            "A chasm runs southwest to northeast and the path follows it. You are on the south side of the chasm, where a crack opens into a passage.", true),
        new(ZorkIds.DampCave, "Damp Cave",
            "This cave has exits to the west and east, and narrows to a crack toward the south. The earth is particularly damp here.", true),
        new(ZorkIds.TwistingPassage, "Twisting Passage",
            "This is a winding passage. It seems that there are only exits on the east and north.", true),
        new(ZorkIds.WindingPassage, "Winding Passage",
            "This is a winding passage. It seems that there are only exits on the east and north.", true),
        new(ZorkIds.NarrowPassage, "Narrow Passage",
            "This is a long and narrow corridor where a long north-south passageway briefly narrows even further.", true),
        new(ZorkIds.ColdPassage, "Cold Passage",
            "This is a cold and damp corridor where a long east-west passageway turns into a southward path.", true),
        new(ZorkIds.MirrorRoom1, "Mirror Room",
            "You are in a large square room with tall ceilings. On the south wall is an enormous mirror which fills the entire wall.", true),
        new(ZorkIds.MirrorRoom2, "Mirror Room",
            "You are in a large square room with tall ceilings. On the north wall is an enormous mirror which fills the entire wall.", false),
        new(ZorkIds.Cave1, "Cave",
            "This is a tiny cave with entrances west and north, and a dark, forbidding staircase leading down.", true),
        new(ZorkIds.Cave2, "Cave",
            "This is a tiny cave with entrances west and north, and a dark, forbidding staircase leading down.", true),
        new(ZorkIds.Temple, "Temple",
            "This is the north end of a large temple. On the east wall is an ancient inscription, probably a prayer in a long-forgotten language. Below the prayer is a staircase leading down. The west wall is solid granite. The exit to the north end of the room is through huge marble pillars.", false),
        new(ZorkIds.Altar, "Altar",
            "This is the south end of a large temple. In front of you is what appears to be an altar. In one corner is a small hole in the floor which leads into darkness. You probably could not get back up it.", false),
        new(ZorkIds.TorchRoom, "Torch Room",
            "This is a large room. Your sword is glowing with a faint blue glow. The only exit is to the west.", true),
        new(ZorkIds.EgyptianRoom, "Egyptian Room",
            "This is a room which looks like an Egyptian tomb. There is an ascending staircase to the west.", true),
        new(ZorkIds.EntranceToHades, "Entrance to Hades",
            "You are outside a large gateway through which is visible a desolate landscape.", false),
        new(ZorkIds.LandOfTheDead, "Land of the Dead",
            "You have entered the Land of the Living Dead. Thousands of lost souls can be heard weeping and moaning. In the corner are stacked the remains of dozens of previous adventurers less fortunate than yourself. A passage exits to the north.", false),

        // Dam / reservoir (10)
        new(ZorkIds.Dam, "Dam",
            "You are standing on the top of the Flood Control Dam #3, which is quite a sight. There are paths to the north, south, and west, and a scramble down.", false),
        new(ZorkIds.DamLobby, "Dam Lobby",
            "This room appears to have been the waiting room for groups touring the dam. There are open doorways here to the north and east marked \"Private\", and there is a path leading south over the top of the dam.", false),
        new(ZorkIds.MaintenanceRoom, "Maintenance Room",
            "This is what appears to have been the maintenance room for Flood Control Dam #3. Apparently, this room has been ransacked recently, for most of the valuable equipment is gone. On the wall in front of you is a group of buttons colored blue, yellow, brown, and red. There are doorways to the west and south.", true),
        new(ZorkIds.DamBase, "Dam Base",
            "You are at the base of Flood Control Dam #3, which looms above you and to the north. The river Frigid is flowing by here. Along the river are the White Cliffs which seem to form giant walls stretching from north to south along the shores of the river as it winds its way downstream.", false),
        new(ZorkIds.Reservoir, "Reservoir",
            "You are on the lake. Beaches can be seen north and south. The water here is deep and cold.", true),
        new(ZorkIds.ReservoirNorth, "Reservoir North",
            "You are in a large cavernous room, north of a large lake. A staircase leads up.", true),
        new(ZorkIds.ReservoirSouth, "Reservoir South",
            "You are in a long room on the south shore of a large lake, far too deep and wide for crossing.", true),
        new(ZorkIds.AtlantisRoom, "Atlantis Room",
            "This is an ancient room, long under water. There is an exit to the south and a staircase leading up.", true),
        new(ZorkIds.Stream, "Stream",
            "You are on the gently flowing stream. The upstream route is too narrow to navigate, and the downstream route is invisible due to twisting walls. There is a narrow beach to land on.", true),
        new(ZorkIds.StreamView, "Stream View",
            "You are standing on a path beside a gently flowing stream. The path follows the stream, which flows from west to east.", false),

        // River / beaches (13)
        new(ZorkIds.River1, "Frigid River",
            "The sound of rushing water is nearly unbearable here. On the east shore is a large landing area.", false),
        new(ZorkIds.FrigidRiver, "Frigid River",
            "The river is running faster here and the sound ahead appears to be that of rushing water. On the east shore is a sandy beach. A small area of beach can also be seen below the cliffs on the west shore.", true),
        new(ZorkIds.River2, "Frigid River",
            "The river descends here into a valley. There is a narrow beach on the west shore below the cliffs. In the distance a faint rumbling can be heard.", true),
        new(ZorkIds.River3, "Frigid River",
            "The river turns a corner here making it impossible to see the Dam. The White Cliffs loom on the east bank and large rocks prevent landing on the west.", true),
        new(ZorkIds.River4, "Frigid River",
            "You are on the Frigid River in the vicinity of the Dam. The river flows quietly here. There is a landing on the west shore.", false),
        new(ZorkIds.Beach1, "White Cliffs Beach",
            "You are on a rocky, narrow strip of beach beside the Cliffs. A narrow path leads north along the shore.", true),
        new(ZorkIds.Beach2, "White Cliffs Beach",
            "You are on a narrow strip of beach which runs along the base of the White Cliffs. There is a narrow path heading south along the Cliffs and a tight passage leading west into the cliffs themselves.", true),
        new(ZorkIds.SandyBeach, "Sandy Beach",
            "You are on a large sandy beach on the east shore of the river, which is flowing quickly by. A path runs beside the river to the south here, and a passage is partially buried in sand to the northeast.", true),
        new(ZorkIds.SandyCave, "Sandy Cave",
            "This is a sand-filled cave whose exit is to the southwest.", true),
        new(ZorkIds.Shore, "Shore",
            "You are on the east shore of the river. The water here seems somewhat treacherous. A path travels from north to south here, the south end quickly turning around a sharp corner.", false),
        new(ZorkIds.AragainFalls, "Aragain Falls",
            "You are at the top of Aragain Falls, an enormous waterfall falling a long way to the rocks below.", false),
        new(ZorkIds.EndOfRainbow, "End of Rainbow",
            "You are on a small, rocky beach on the continuation of the Frigid River past the Falls. The beach is narrow due to the presence of the White Cliffs. The river canyon opens here and sunlight shines in from above. A rainbow crosses over the falls to the east and a narrow path continues to the southwest.", false),
        new(ZorkIds.OnTheRainbow, "On the Rainbow",
            "You are on top of a rainbow (I bet you never thought you would walk on a rainbow), with a magnificent view of the Falls. The rainbow travels east-west here.", false),

        // Coal mine (17)
        new(ZorkIds.SlideRoom, "Slide Room",
            "This is a small chamber, which appears to have been part of a coal mine. On the south wall the letters \"Granite Wall\" are etched in the rock.", true),
        new(ZorkIds.MineEntrance, "Mine Entrance",
            "You are standing at the entrance of what might have been a coal mine. The shaft enters the west wall, and there is another exit on the south end of the room.", true),
        new(ZorkIds.SqueakyRoom, "Squeaky Room",
            "You are in a small room. Strange squeaky sounds may be heard close by.", true),
        new(ZorkIds.BatRoom, "Bat Room",
            "You are in a small room which has doors only to the east and south.", true),
        new(ZorkIds.Mine1, "Coal Mine", "This is a nondescript part of a coal mine.", true),
        new(ZorkIds.Mine2, "Coal Mine", "This is a nondescript part of a coal mine.", true),
        new(ZorkIds.Mine3, "Coal Mine", "This is a nondescript part of a coal mine.", true),
        new(ZorkIds.Mine4, "Coal Mine", "This is a nondescript part of a coal mine.", true),
        new(ZorkIds.GasRoom, "Gas Room",
            "This is a small room which smells strongly of coal gas. There is a short climb up some rocks and a narrow passage leading east.", true),
        new(ZorkIds.SmellyRoom, "Smelly Room",
            "This is a small non-descript room. The air is slightly tainted.", true),
        new(ZorkIds.ShaftRoom, "Shaft Room",
            "This is a large room, in the middle of which is a small shaft descending through darkness.", true),
        new(ZorkIds.LadderTop, "Ladder Top", "This is a very small room. In one corner is a rickety wooden ladder, leading downward.", true),
        new(ZorkIds.LadderBottom, "Ladder Bottom",
            "This is a rather wide room. On one side is the bottom of a narrow wooden ladder. To the west and the south are passages leaving the room.", true),
        new(ZorkIds.TimberRoom, "Timber Room",
            "This is a long and narrow passage, which is cluttered with broken timbers. A wide passage comes from the east and turns at the west end of the room into a very narrow passageway. From the west comes a strong draft.", true),
        new(ZorkIds.DeadEnd, "Dead End",
            "You have come to a dead end in the mine.", true),
        new(ZorkIds.DraftyRoom, "Drafty Room",
            "This is a small drafty room in which is the bottom of a long shaft. To the south is a passageway and to the east a very narrow passage. In the shaft can be seen a heavy iron chain.", true),
        new(ZorkIds.MachineRoom, "Machine Room",
            "This is a large, cold room whose sole exit is to the north. On the west side of the room is a machine which is connected to a large pipe.", true),
    ];
}
